version: '3.8'
services:
  # Eureka Discovery Service
  discovery-service:
    build: ./discovery-service
    ports:
      - "8761:8761"  # Eureka Discovery service port
    networks:
      - microservices-net

  # Gateway Service
  gateway-service:
    build: ./gateway-service
    ports:
      - "8888:8888"  # Gateway port
    depends_on:
      - discovery-service
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery-service:8761/eureka/
    networks:
      - microservices-net

  # Project Service
  project-service:
    build: ./project-service
    ports:
      - "8081:8081"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery-service:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://projetdb:3306/construction_project
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
    depends_on:
      - discovery-service
      - projetdb
    networks:
      - microservices-net

  # Task Service
  tache-service:
    build: ./task-service
    ports:
      - "8082:8082"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery-service:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://tachedb:3306/construction_task
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
    depends_on:
      - discovery-service
      - tachedb
    networks:
      - microservices-net

  # Resource Service
  resource-service:
    build: ./resource-service
    ports:
      - "8083:8083"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery-service:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://ressourcedb:3306/construction_resource
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
    depends_on:
      - discovery-service
      - ressourcedb
    networks:
      - microservices-net

  # User Service
  user-service:
    build: ./user-service
    ports:
      - "8087:8087"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery-service:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://user-db:3306/construction_user
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
    depends_on:
      - discovery-service
      - userdb
    networks:
      - microservices-net
    deploy:
      restart_policy:
        condition: on-failure

  # Databases for each service
  projetdb:
    image: "mysql:8"
    environment:
      MYSQL_DATABASE: construction_project
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - projet-db:/var/lib/mysql
    networks:
      - microservices-net

  ressourcedb:
    image: "mysql:8"
    environment:
      MYSQL_DATABASE: construction_resource
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ressource-db:/var/lib/mysql
    networks:
      - microservices-net

  tachedb:
    image: "mysql:8"
    environment:
      MYSQL_DATABASE: construction_task
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - tache-db:/var/lib/mysql
    networks:
      - microservices-net

  userdb:
    image: "mysql:8"
    environment:
      MYSQL_DATABASE: construction_user
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - user-db:/var/lib/mysql
    networks:
      - microservices-net

volumes:
  projet-db:
  ressource-db:
  tache-db:
  user-db:

networks:
  microservices-net:
    driver: bridge
